### ISSUE TITLE
Random NPE after Don't Save End

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#136]
Every now and then I get a NullPointerException at a Don't Save End node. It stays in yellow / configured mode then. Using a Table Cell Viewer on the data behind it does not help, but the unchanged data right in front of it seems to be accessible.

After re-execution of the Don't Save Start Node, the error was gone, but it occurred the third time now.

```
ERROR	 LocalNodeExecutionJob         	 Caught "NullPointerException": Argument must not be null.
DEBUG	 LocalNodeExecutionJob         	 Caught "NullPointerException": Argument must not be null.
java.lang.NullPointerException: Argument must not be null.
	at org.knime.core.data.filestore.internal.ReferenceWriteFileStoreHandler.<init>(ReferenceWriteFileStoreHandler.java:72)
	at org.knime.core.node.workflow.NativeNodeContainer.initFileStore(NativeNodeContainer.java:713)
	at org.knime.core.node.workflow.NativeNodeContainer.performStateTransitionEXECUTING(NativeNodeContainer.java:416)
	at org.knime.core.node.workflow.WorkflowManager.doBeforeExecution(WorkflowManager.java:2816)
	at org.knime.core.node.workflow.NodeContainer.notifyParentExecuteStart(NodeContainer.java:505)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:149)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:125)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:248)
```

**Comment by dietzc** [comment]
Latest nightly built?

**Comment by maierl** [comment]
Tested on nightly 1.3.0.201504212308.

**Comment by dietzc** [comment]
we fixed a similar bug in https://github.com/knime-ip/knip/commit/9bf991d127ecfc3b6f826c121e65d13e5f6abf12 19days ago. So this might be solving your problem. your nightly seems to be 6 weeks old.
