### ISSUE TITLE
NPE on groupBy

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#149]
In Knime 2.12 and stable KNIP, groupBy throws a NullPointerException in [this workflow](https://powerfolder.dkfz.de/dl/fiGbqfDjWbWKb8RsLWibRMvt/npe_on_groupBy.zip).

```
DEBUG GroupBy              2:989      Execute failed: ("ArrayIndexOutOfBoundsException"): null
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.knime.knip.base.data.aggregation.ImgMergeOperator$UnsignedShortTypeHandler.copyData(ImgMergeOperator.java:424)
	at org.knime.knip.base.data.aggregation.ImgMergeOperator$UnsignedShortTypeHandler.copyData(ImgMergeOperator.java:1)
	at org.knime.knip.base.data.aggregation.ImgMergeOperator.computeInternal(ImgMergeOperator.java:579)
	at org.knime.base.data.aggregation.AggregationOperator.compute(AggregationOperator.java:306)
	at org.knime.base.node.preproc.groupby.BigGroupByTable.createGroupByTable(BigGroupByTable.java:272)
	at org.knime.base.node.preproc.groupby.GroupByTable.<init>(GroupByTable.java:217)
	at org.knime.base.node.preproc.groupby.GroupByTable.<init>(GroupByTable.java:120)
	at org.knime.base.node.preproc.groupby.BigGroupByTable.<init>(BigGroupByTable.java:118)
	at org.knime.base.node.preproc.groupby.GroupByNodeModel.createGroupByTable(GroupByNodeModel.java:683)
	at org.knime.base.node.preproc.groupby.GroupByNodeModel.createGroupByTable(GroupByNodeModel.java:646)
	at org.knime.base.node.preproc.groupby.GroupByNodeModel.createGroupByTable(GroupByNodeModel.java:627)
	at org.knime.base.node.preproc.groupby.GroupByNodeModel.execute(GroupByNodeModel.java:609)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:563)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1136)
	at org.knime.core.node.Node.execute(Node.java:932)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:554)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
```

**Comment by dietzc** [comment]
thx! fixed!
