### ISSUE TITLE
Image Properties: NPE

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#163]
My minimal workflow at https://powerfolder.dkfz.de/dl/fi2mon3vAPgkBQ93tDroJvX7/bug.zip throws an NPE at the Image Properties Node and "Potential deadlock in SWT Display". Log file is included.

Tested on the stable and the latest nightly build.

**Comment by maierl** [comment]
the NPE does not occur anymore when the origian images are read with the nightly, as opposed to the input table stored previously with the stable version.

**Comment by maierl** [comment]
just produced another unreadable image + npe on the nightly.
https://powerfolder.dkfz.de/dl/fiGHzZ4AnnebcfpkAjMVmaZd/img_broken_again.zip

**Comment by maierl** [comment]
trying to have a closer look at row containing the broken image didn't show any content in the out port viewer, even with the image columns removed. the 'cache' node allowed to view the strings then.

when I call it with the images included, I get a stack trace at last

```
ERROR Cache                0:939:977  Cannot read image.
DEBUG Cache                0:939:977  Cannot read image.
java.io.IOException: No externalizer available with id 
	at org.knime.knip.core.io.externalization.ExternalizerManager.read(ExternalizerManager.java:201)
	at org.knime.knip.base.data.img.ImgPlusCell.readImgData(ImgPlusCell.java:605)
	at org.knime.knip.base.data.img.ImgPlusCell.getStringValue(ImgPlusCell.java:445)
	at org.knime.knip.base.data.img.ImgPlusCell.toString(ImgPlusCell.java:693)
	at org.knime.core.data.renderer.AbstractPainterDataValueRenderer.getTableCellRendererComponent(AbstractPainterDataValueRenderer.java:202)
	at org.knime.core.data.renderer.DefaultDataValueRendererFamily.getTableCellRendererComponent(DefaultDataValueRendererFamily.java:217)
	at org.knime.core.data.renderer.SetOfRendererFamilies.getTableCellRendererComponent(SetOfRendererFamilies.java:138)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at org.knime.core.node.tableview.TableContentView.prepareRenderer(TableContentView.java:287)
	at org.knime.core.node.tableview.TableContentView.fitCellSizeToRenderer(TableContentView.java:999)
	at org.knime.core.node.tableview.TableContentView.tableChanged(TableContentView.java:1020)
	at javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableStructureChanged(Unknown Source)
	at org.knime.core.node.tableview.TableContentModel.setDataTableIntern(TableContentModel.java:413)
	at org.knime.core.node.tableview.TableContentModel.access$1(TableContentModel.java:342)
	at org.knime.core.node.tableview.TableContentModel$1.run(TableContentModel.java:315)
	at org.knime.core.node.util.ViewUtils.invokeAndWaitInEDT(ViewUtils.java:134)
	at org.knime.core.node.tableview.TableContentModel.setDataTable(TableContentModel.java:312)
	at org.knime.core.node.tableview.TableContentView.setDataTable(TableContentView.java:310)
	at org.knime.core.node.tableview.TableView.setDataTable(TableView.java:427)
	at org.knime.core.node.workflow.BufferedDataTableView.updateDataTable(BufferedDataTableView.java:93)
	at org.knime.core.node.workflow.BufferedDataTableView.<init>(BufferedDataTableView.java:88)
	at org.knime.core.node.BufferedDataTable.getViews(BufferedDataTable.java:865)
	at org.knime.core.node.workflow.OutPortView$4.runWithContext(OutPortView.java:257)
	at org.knime.core.node.workflow.OutPortView$4.run(OutPortView.java:243)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by maierl** [comment]
the broken images seem to be hard to reproduce. merely re-executing the workflow from the last node that modified the images (Splitter) helped, this time.
Interestingly, the loop end node executed instantly this time as opposed to writing lots of image data last time. Back then, one of the input images was already broken prior to the loop end node.

**Comment by dietzc** [comment]
are you mixing versions of nightly/stable somehow? so saved workflow in (Nightly) and loaded with stable? This is a really interesting bug.

**Comment by maierl** [comment]
the first example did mix the stable and nightly, whereas the second didn't. yet, the error happens only rarely, so it is hard to confirm.

**Comment by dietzc** [comment]
@maierl closing for now. let me know if this pops up in 1.4.0 again.
