### ISSUE TITLE
Urgent: Table Writer: EOFException

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#253]
When I store my image + segmentation results with a TableWriter and read them with a Table Reader, everything seems to be fine. But when I want to look at the results with the Interactive Segmentation View, I get an EOFException.

```
ERROR Interactive Segmentation View 3:1666:118 Execute failed: java.io.EOFException
DEBUG Interactive Segmentation View 3:1666:118 Execute failed: java.io.EOFException
java.lang.RuntimeException: java.io.EOFException
	at org.knime.knip.base.data.CachedObjectAccess.get(CachedObjectAccess.java:154)
	at org.knime.knip.base.data.img.ImgPlusCell.getDimensions(ImgPlusCell.java:250)
	at org.knime.knip.base.nodes.view.segmentoverlay.SegmentOverlayNodeModel.execute(SegmentOverlayNodeModel.java:250)
	at org.knime.core.node.NodeModel.execute(NodeModel.java:719)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:563)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1136)
	at org.knime.core.node.Node.execute(Node.java:932)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:554)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: java.io.EOFException
	at org.knime.knip.core.io.externalization.BufferedDataInputStream.read(BufferedDataInputStream.java:133)
	at org.knime.knip.core.io.externalization.BufferedDataInputStream.readInt(BufferedDataInputStream.java:187)
	at org.knime.knip.core.io.externalization.ExternalizerManager.readString(ExternalizerManager.java:289)
	at org.knime.knip.core.io.externalization.ExternalizerManager.read(ExternalizerManager.java:204)
	at org.knime.knip.base.data.CachedObjectAccess.get(CachedObjectAccess.java:147)
	... 16 more
```

I stored a simplified workflow with data at https://powerfolder.dkfz.de/dl/fi5AvMjwyeZPD9FjBqsDQhyF/savingFail.tgz

Would you *please* fix that bug for me?

**Comment by dietzc** [comment]
1k/h ;-) I will have a look at latest tomorrow.

**Comment by dietzc** [comment]
Which KNIME? Which KNIP? I can't reproduce the problem locally!

**Comment by gab1one** [comment]
I just tried to reproduce the bug, I manually selected the storage location for the ``.table`` files and it worked without a flaw. Maybe the storage location is faulty?

**Comment by maierl** [comment]
@dietzc Thanks for helping to reproduce!

**Comment by maierl** [comment]
The missing ingredient was to set the maximum (image) file size to a value other than zero.

**Comment by maierl** [comment]
Any progress already on that bug?

**Comment by dietzc** [comment]
I will work on it today. Does the workaround I showed you still do the job?

**Comment by maierl** [comment]
Locally yes, didn't test it on the cluster though as it has no SSDs. Thanks for your help!

**Comment by dietzc** [comment]
I tracked down the problem and it seems to be something in the KNIME Analytics Platform core. Storing multiple images into a single file is not yet fully supported by the KNIME Analytics Platform core. So I don't see this "bug" being fixed soon.

Therefore let's talk about workarounds: Do you have to store the bitmasks / labeling in this table, too? Why do you store the table to disc anyway? Can't you simply connect the output of the feature node to the input of the other node?

**Comment by maierl** [comment]
That's not exactly what I hoped for. I want to use the cluster for preparing the input data (segmentation + features) for training a classifier.

**Comment by dietzc** [comment]
do you need the bitmask / labeling in the written table?

**Comment by maierl** [comment]
Yes, for selecting the classification of the segments within the images.

**Comment by dietzc** [comment]
for selecting training data you mean? Isn't the Labeling enough for this task (`LabelingEditor`)?

**Comment by maierl** [comment]
I assumed the labeling had the same bug as the Bitmasks. Those could anyway be derived from the labeling again if necessary, right?

**Comment by dietzc** [comment]
This is not really a bug. Writing several cells into a single file is just not the intended behaviour (, yet). If you only write the labeling, you can set the filesize = 0 and then there will be no bug at all. and yes, you can derive the segments again ;-)

**Comment by maierl** [comment]
The file size also affects the temp folder and run time. Could I set that option dynamically just before writing the table?

If I only write a single labeling per file, that would not depend on the max file size setting and could be a workaround, right?

If it crashes without telling me why, that is a big in my eyes.

**Comment by dietzc** [comment]
if you only store the `Labeling` and actually never produce the bitmask in during feature extraction, you should be fine with filesize = 0.

**Comment by maierl** [comment]
Any image will be problematic when saved with file size > 0 mb, right?

Why do I need both file size = 0 and no Bitmasks? I didn't spot the option to avoid generating Bitmasks, but excluding them before saving the table should do the trick?

**Comment by dietzc** [comment]
because the problems has nothing to do with the bitmask directly. it stems from the fact, that with filesize > 0 you are writing more than one image or labeling per file.

excluding them before saving should do the trick, yes.

**Comment by dietzc** [comment]
Solved with a workaround!
