### ISSUE TITLE
Feature Calculator (BETA): No compatible service: org.knime.knip.features.FeatureService

### ISSUE THREAD

**Issue by seebacherd** [knime-ip/knip#319]
Hello together,

I'm trying to get KNIP running on Windows 10. I imported the projects knip, knip-sdk-setup and knip-scijava (master branch on everything). I'm using the knip-sdk-nightly-dev.target where I selected everything from https://community.knime.org/download/knip-externals-trunk, and the things I needed from https://update.knime.org/analytics-platform/3.1/ and http://update.knime.org/server/4.2.

Everything appears to work, the KNIP nodes like Image Reader etc. are running fine, but the Feature Calculator (Beta) throws an IllegalArgumentException when I try to connect it with other nodes with the message: No compatible service: org.knime.knip.features.FeatureService. I can open the dialog afterwards, but it appears to be broken, I can't add any FeatureSets.

I've included the full StackStrace of the Exception:

`
java.lang.IllegalArgumentException: No compatible service: org.knime.knip.features.FeatureService
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:243)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:170)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.knime.knip.features.FeaturesGateway.<init>(FeaturesGateway.java:85)
	at org.knime.knip.features.FeaturesGateway.getInstance(FeaturesGateway.java:92)
	at org.knime.knip.features.FeaturesGateway.fs(FeaturesGateway.java:105)
	at org.knime.knip.features.node.FeatureCalculatorModel.configure(FeatureCalculatorModel.java:228)
	at org.knime.core.node.NodeModel.configure(NodeModel.java:1088)
	at org.knime.core.node.NodeModel.configureModel(NodeModel.java:1037)
	at org.knime.core.node.Node.invokeNodeModelConfigure(Node.java:1815)
	at org.knime.core.node.Node.configure(Node.java:1751)
	at org.knime.core.node.workflow.NativeNodeContainer.performConfigure(NativeNodeContainer.java:527)
	at org.knime.core.node.workflow.SingleNodeContainer.callNodeConfigure(SingleNodeContainer.java:292)
	at org.knime.core.node.workflow.SingleNodeContainer.configure(SingleNodeContainer.java:177)
	at org.knime.core.node.workflow.WorkflowManager.configureSingleNodeContainer(WorkflowManager.java:5884)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7800)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7637)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7763)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7637)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7589)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7513)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7486)
	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7338)
	at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:154)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
`

**Comment by gab1one** [comment]
Hi @seebacherd can you try to update the knip-sdk-setup project and try the ``knip-sdk-nightly-full.target``?

**Comment by seebacherd** [comment]
Unfortunately, that didn't solve the problem. Still the same error.

**Comment by dietzc** [comment]
fixed.
