### ISSUE TITLE
Interactive Annotator: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#347]
When executing the Interactive Annotator, I get an exception:
```
ERROR Interactive Annotator 2:1534     Error in row Row1: 2
DEBUG Interactive Annotator 2:1534     Error in row Row1: 2
java.lang.ArrayIndexOutOfBoundsException: 2
	at org.knime.knip.core.ui.imgviewer.overlay.Overlay.renderSegmentationImage(Overlay.java:320)
	at org.knime.knip.io.nodes.annotation.create.OverlayAnnotatorNodeModel.compute(OverlayAnnotatorNodeModel.java:165)
	at org.knime.knip.io.nodes.annotation.create.OverlayAnnotatorNodeModel.compute(OverlayAnnotatorNodeModel.java:1)
	at org.knime.knip.base.node.ValueToCellNodeModel$1.getCells(ValueToCellNodeModel.java:376)
	at org.knime.core.data.container.RearrangeColumnsTable.calcNewCellsForRow(RearrangeColumnsTable.java:503)
	at org.knime.core.data.container.RearrangeColumnsTable.calcNewColsSynchronously(RearrangeColumnsTable.java:424)
	at org.knime.core.data.container.RearrangeColumnsTable.create(RearrangeColumnsTable.java:342)
	at org.knime.core.node.ExecutionContext.createColumnRearrangeTable(ExecutionContext.java:370)
	at org.knime.knip.base.node.ValueToCellNodeModel.execute(ValueToCellNodeModel.java:541)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:563)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1146)
	at org.knime.core.node.Node.execute(Node.java:933)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:556)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
DEBUG Interactive Annotator 2:1534     reset
ERROR Interactive Annotator 2:1534     Execute failed: java.lang.ArrayIndexOutOfBoundsException: 2
DEBUG Interactive Annotator 2:1534     Execute failed: java.lang.ArrayIndexOutOfBoundsException: 2
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.knime.knip.base.node.ValueToCellNodeModel$1.getCells(ValueToCellNodeModel.java:399)
	at org.knime.core.data.container.RearrangeColumnsTable.calcNewCellsForRow(RearrangeColumnsTable.java:503)
	at org.knime.core.data.container.RearrangeColumnsTable.calcNewColsSynchronously(RearrangeColumnsTable.java:424)
	at org.knime.core.data.container.RearrangeColumnsTable.create(RearrangeColumnsTable.java:342)
	at org.knime.core.node.ExecutionContext.createColumnRearrangeTable(ExecutionContext.java:370)
	at org.knime.knip.base.node.ValueToCellNodeModel.execute(ValueToCellNodeModel.java:541)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:563)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1146)
	at org.knime.core.node.Node.execute(Node.java:933)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:556)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.knime.knip.core.ui.imgviewer.overlay.Overlay.renderSegmentationImage(Overlay.java:320)
	at org.knime.knip.io.nodes.annotation.create.OverlayAnnotatorNodeModel.compute(OverlayAnnotatorNodeModel.java:165)
	at org.knime.knip.io.nodes.annotation.create.OverlayAnnotatorNodeModel.compute(OverlayAnnotatorNodeModel.java:1)
	at org.knime.knip.base.node.ValueToCellNodeModel$1.getCells(ValueToCellNodeModel.java:376)
	... 18 more
```

**Comment by dietzc** [comment]
it would help tremendously if you could provide us the following information:

Which version of KNIME / KNIP?
How to reproduce the error?

**Comment by maierl** [comment]
Knime: 3.1.2, Knip: 1.4.1.201604050950.
The last time I used this workflow was on an earlier version of Knime, 3.1.1 or 3.1.0. Back then it was running fine. [Example workflow](https://powerfolder.dkfz.de/dl/fiJ5jsrdqM1j4ZF9UXQihvFu/annotator_out_of_bounds.zip)

**Comment by dietzc** [comment]
thanks. I will have a look asap.

**Comment by dietzc** [comment]
did you first read 3D images and then you splitted them?

**Comment by maierl** [comment]
The images were only 2D in the first place.

**Comment by maierl** [comment]
any update on this?

**Comment by dietzc** [comment]
I have no idea since now. I worked on it a bit, but I was not really able to reproduce. I will give it another try before the release!

**Comment by maierl** [comment]
Hmm, strange. I'll check it on a different system then, maybe that helps... Thanks for trying though!

**Comment by maierl** [comment]
Ok, seems partly my fault: deleted all the old labels, now it works fine. Where are those labels saved by the way?

**Comment by dietzc** [comment]
in the SettingsModel?! Hm so the bug is rather, that the labels are still present if the image changes?

**Comment by maierl** [comment]
Sometimes it can be useful to keep the annotation for another image with the same Row Id, but that’s probably not intended behavior.

 

Btw: there’s no way to programmatically generate labels at given x/y positions, right?

**Comment by dietzc** [comment]
oh you can do that using loops and the groupby! but this is a different topic, right? can you open a topic in the forum for that or an issue if it is a bug?
