### ISSUE TITLE
Python Script Node fails for large images

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#390]
With a 512x512x299x8 xyzc image in this [example workflow](https://github.com/knime-ip/knip/files/390666/python.img.dim.fail.knwf.txt), the Python Script (1:1) node fails with

``` java
java.lang.IllegalArgumentException
    at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
    at io.scif.io.ByteArrayHandle.setLength(ByteArrayHandle.java:115)
    at io.scif.io.AbstractNIOHandle.validateLength(AbstractNIOHandle.java:74)
    at io.scif.io.ByteArrayHandle.write(ByteArrayHandle.java:366)
    at io.scif.io.ByteArrayHandle.write(ByteArrayHandle.java:359)
    at io.scif.io.RandomAccessOutputStream.write(RandomAccessOutputStream.java:122)
    at io.scif.formats.tiff.TiffSaver.writeImageIFD(TiffSaver.java:520)
    at io.scif.formats.tiff.TiffSaver.writeImage(TiffSaver.java:399)
    at io.scif.formats.tiff.TiffSaver.writeImage(TiffSaver.java:276)
    at io.scif.formats.TIFFFormat$Writer.savePlane(TIFFFormat.java:1366)
    at io.scif.formats.TIFFFormat$Writer.writePlane(TIFFFormat.java:1459)
    at io.scif.AbstractWriter.savePlane(AbstractWriter.java:168)
    at io.scif.AbstractWriter.savePlane(AbstractWriter.java:159)
    at io.scif.img.ImgSaver.writePlanes(ImgSaver.java:684)
    at io.scif.img.ImgSaver.writeImg(ImgSaver.java:541)
    at io.scif.img.ImgSaver.writeImg(ImgSaver.java:527)
    at io.scif.img.ImgSaver.writeImg(ImgSaver.java:461)
    at io.scif.img.ImgSaver.saveImg(ImgSaver.java:243)
    at io.scif.img.ImgSaver.saveImg(ImgSaver.java:222)
    at org.knime.knip.knimepython.ImgPlusSerializer$1.serialize(ImgPlusSerializer.java:89)
    at org.knime.knip.knimepython.ImgPlusSerializer$1.serialize(ImgPlusSerializer.java:1)
    at org.knime.python.kernel.ProtobufConverter.dataTableToProtobuf(ProtobufConverter.java:389)
    at org.knime.python.kernel.PythonKernel.putDataTable(PythonKernel.java:461)
    at org.knime.python.kernel.PythonKernelManager$5.run(PythonKernelManager.java:254)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
    at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
```

**Comment by dietzc** [comment]
true. only works for images < Integer.MAX pixels.

**Comment by dietzc** [comment]
wrong project. please open bug in https://github.com/knime-ip/knip-python-extensions if still present
