### ISSUE TITLE
ImageWrite throws ArrayIndexOutOfBoundsException on composed images

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#422]
When composing an image using the _GroupBy_ node, without using a predefined interval, and then trying to write the resulting image with the image writer, the following exception gets thrown:

```
2016-11-16 10:20:48,042 : DEBUG : KNIME-Worker-4971 : Image Writer : Image Writer : 4:9 : Execute failed: ("ArrayIndexOutOfBoundsException"): -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at io.scif.formats.TIFFFormat$Writer.savePlane(TIFFFormat.java:1425)
	at io.scif.formats.TIFFFormat$Writer.writePlane(TIFFFormat.java:1532)
	at io.scif.AbstractWriter.savePlane(AbstractWriter.java:170)
	at io.scif.AbstractWriter.savePlane(AbstractWriter.java:161)
	at io.scif.img.ImgSaver.writePlanes(ImgSaver.java:681)
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:542)
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:528)
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:497)
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:459)
	at io.scif.img.ImgSaver.saveImg(ImgSaver.java:174)
	at io.scif.img.ImgSaver.saveImg(ImgSaver.java:158)
	at org.knime.knip.io.nodes.imgwriter2.ImgWriter2.writeImage(ImgWriter2.java:340)
	at org.knime.knip.io.nodes.imgwriter2.ImgWriter2.writeImage(ImgWriter2.java:231)
	at org.knime.knip.io.nodes.imgwriter2.ImgWriter2NodeModel.run(ImgWriter2NodeModel.java:345)
	at org.knime.knip.io.nodes.imgwriter2.ImgWriter2NodeModel.execute(ImgWriter2NodeModel.java:237)
	at org.knime.core.node.NodeModel.execute(NodeModel.java:732)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:566)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1128)
	at org.knime.core.node.Node.execute(Node.java:915)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:556)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
```

Here is an example workflow:
[Image Writer Bugs.zip](https://github.com/knime-ip/knip/files/594160/Image.Writer.Bugs.zip)

**Comment by gab1one** [comment]
Hi @imagejan,
thank you for reporting this bug,  I could reproduce it and am working on a fix. Until that is released you can use the **Set Image Metadata** node to work around this issue, see the attached example workflow on how to do it. It will set the labels of the axes to "X" and "Y".

[Image Writer Bug Workaround.zip](https://github.com/knime-ip/knip/files/622285/Image.Writer.Bug.Workaround.zip)
