### ISSUE TITLE
Image Reader: No compatible service for >4GB TIFF

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#452]
When I try to read a >4 GB TIFF with the latest KNIP stable with Cell Img Factory, I get
```
DEBUG Image Reader (Table) 0:2667:2272:2256 Encountered exception while reading image:
java.lang.IllegalArgumentException: No compatible service: io.scif.SCIFIOService
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:243)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:194)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:170)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at io.scif.img.AbstractImgIOComponent.<init>(AbstractImgIOComponent.java:57)
	at io.scif.img.ImgOpener.<init>(ImgOpener.java:94)
	at io.scif.img.IO.opener(IO.java:382)
	at io.scif.img.IO.openImgs(IO.java:78)
	at io.scif.img.IO.open(IO.java:417)
	at org.knime.knip.io.ScifioImgSource.getImg(ScifioImgSource.java:262)
	at org.knime.knip.io.nodes.imgreader2.AbstractReadImgFunction.readImageAndMetadata(AbstractReadImgFunction.java:138)
```
with the Array / Planar Img Factory, it fails as expected:
```
DEBUG Image Reader (Table) 0:2667:2272:2256 Encountered exception while reading image:
java.lang.IndexOutOfBoundsException: Index: 36, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at io.scif.formats.MinimalTIFFFormat$Reader.openPlane(MinimalTIFFFormat.java:611)
	at io.scif.formats.MinimalTIFFFormat$Reader.openPlane(MinimalTIFFFormat.java:533)
	at io.scif.AbstractReader.openPlane(AbstractReader.java:167)
	at io.scif.filters.ChannelFiller.openPlane(ChannelFiller.java:171)
```

**Comment by imagejan** [comment]
See also https://github.com/knime-ip/knip/issues/353
